export const myProjects = [
  {
    projectTitle: "My Reads",
    category: ["react"],
    link: "https://my-reads-yehia.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/MyReads",
    imgPath: "../../assets/images/my-reads.png",
  },
  {
    projectTitle: "Expense Tracking",
    category: ["react"],
    link: "https://expense-tracking-yehia.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/Expense-Tracking",
    imgPath: "../../assets/images/expense-tracking.png",
  },
  {
    projectTitle: "Osman Bey",
    category: ["react"],
    link: "https://food-order-app-yehia.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/Food-Order-App",
    imgPath: "../../assets/images/Osman-Bey.png",
  },
  {
    projectTitle: "Todo List",
    category: ["react"],
    link: "https://todo-list-yehia.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/Course-Goal",
    imgPath: "../../assets/images/todo-list.png",
  },
  {
    projectTitle: "Mapty",
    category: ["js"],
    link: "https://yehia-map-activity.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/Mapty",
    imgPath: "../../assets/images/Mapty.png",
  },
  {
    projectTitle: "Pig Game",
    category: ["js"],
    link: "https://yehia-pig-game.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/PIG-Game",
    imgPath: "../../assets/images/Pig-Game.png",
  },
  {
    projectTitle: "video-game-db",
    category: ["ng"],
    link: "https://ng-video-game-db-yehia.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/ng-video-game-db",
    imgPath: "../../assets/images/video-game-db.png",
  },
  {
    projectTitle: "Forkify",
    category: ["ng"],
    link: "https://forkify-angular-app.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/Forkify-Angular",
    imgPath: "../../assets/images/forkify.png",
  },
  {
    projectTitle: "Tour Of Heros",
    category: ["ng"],
    link: "https://tour-of-heros-yehia.netlify.app/dashboard",
    githubLink: "https://github.com/Yehia-Ahmad/Tour-Of-Heroes",
    imgPath: "../../assets/images/tour-of-heros.png",
  },
  {
    projectTitle: "Template Driven Form",
    category: ["ng"],
    link: "https://tamplate-driven-form.netlify.app/",
    githubLink: "https://github.com/Yehia-Ahmad/Template-Driven-Form",
    imgPath: "../../assets/images/template-driven-form.png",
  },
];
